# Same as Black.
line-length = 100
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[lint]
# See https://docs.astral.sh/ruff/rules/ for list of rule codes
# select codes are prefixes, ie "E4" means all E4xx rules
select = [
"E", "F", "A", "DTZ"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "single"
indent-style = "tab"
skip-magic-trailing-comma = false
# require '\n' line endings
line-ending = "lf"
docstring-code-format = false
docstring-code-line-length = "dynamic"