max_width = 100
use_small_heuristics = "Max"
# NOTE: use_small_heuristics controls the following entries as a function of `max_width`: fn_call_width, attr_fn_like_width, struct_lit_width, struct_variant_width, array_width, chain_width, single_line_if_else_max_width
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
combine_control_expr = true
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
doc_comment_code_block_width = 100
edition = "2024"
style_edition = "2024"
empty_item_single_line = true
enum_discrim_align_threshold = 0
error_on_line_overflow = false
error_on_unformatted = false
fn_params_layout = "Compressed"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = false
format_generated_files = false
format_macro_bodies = true
format_macro_matchers = true
format_strings = false
generated_marker_line_search_limit = 5
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Preserve"
imports_granularity = "Module"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = false
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
normalize_comments = false
normalize_doc_attributes = false
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 20
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = false
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = false
wrap_comments = false

